config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root             "static_pages#home"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"

  resources :activities
  resources :subjects
  resources :users, only: [:index, :show, :update]
  resources :courses, only: [:show]
  resources :courses_subjects
  resources :users_subjects

  namespace :supervisor do
    root "courses#index"
    resources :activities
    resources :users, only: [:index, :destroy]
    resources :subjects
    resources :courses do
      resources :courses_subjects, only: [:show, :edit, :update]
      resource :assign_supervisors, only: [:show, :update]
      resource :assign_trainees, only: [:show, :update]
    end
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) {controller && controller.current_user}
  acts_as_paranoid

  validates :name, presence: true
  validates :description, presence: true
  has_many :tasks , dependent: :destroy
  has_many :users_subject
  has_many :users, through: :users_subject
  has_many :courses_subjects, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :load_subject, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.all
  end

  def new
    @subject = Subject.new
    @subject.tasks.build
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      redirect_to subjects_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      redirect_to subjects_path
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    redirect_to subjects_url
  end

  private
  def subject_params
    params.require(:subject).permit :id, :name, :description,
      tasks_attributes: [ :id, :name, :subject_id, :_destroy]
  end

  def load_subject
    @subject = Subject.find params[:id]
  end
end

app/controllers/supervisor/assign_supervisors_controller.rb
class Supervisor::AssignSupervisorsController < ApplicationController
  before_action :load_course
  before_action :check_course
  before_action :load_users

  def show
  end

  def update
    if @course.update_attributes course_params
      @course.assigned_users.each do |user|
        UserMailer.delay.assigned_supervisors user.full_name, user.email, 
          @course.id
      end
      @course.removed_users.each do |user|
        UserMailer.delay.removed_supervisors user.full_name, user.email, 
          @course.id
      end
      redirect_to supervisor_course_path @course
    else
      render :show
    end
  end

  private
  def load_course
    @course = Course.find params[:course_id]
  end

  def load_users
    @users = User.supervisor
  end

  def course_params
    params.require(:course).permit user_ids: []
  end

  def check_course
    if @course.finished?
      flash[:danger] = t "flash_assign_supervisors"
      redirect_to supervisor_course_path @course
    end
  end
end

app/controllers/supervisor/assign_trainees_controller.rb
class Supervisor::AssignTraineesController < ApplicationController
  before_action :load_course
  before_action :check_course
  before_action :load_users

  def show
  end

  def update
    if @course.update_attributes course_params
      @course.assigned_users.each do |user|
        UserMailer.delay.assigned_trainees user.full_name, user.email, @course.id
      end
      @course.removed_users.each do |user|
        UserMailer.delay.removed_trainees user.full_name, user.email, @course.id
      end
      redirect_to supervisor_course_path @course
    else
      render :show
    end
  end

  private
  def load_course
    @course = Course.find params[:course_id]
  end

  def load_users
    @users = User.assignable_trainees @course
  end

  def course_params
    params.require(:course).permit user_ids: []
  end

  def check_course
    if @course.started?
      flash[:danger] = t "flash_assign_trainees"
      redirect_to supervisor_course_path @course
    end
  end
end

app/controllers/supervisor/courses_controller.rb
class Supervisor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_course, except: [:index, :new, :create]
  before_action :check_course_before_update, only: :update
  before_action :check_course_before_destroy, only: :destroy
  load_and_authorize_resource only: [:edit, :update, :destroy]

  def index
    @search = current_user.courses.search params[:q]
    @courses = @search.result.paginate page: params[:page], per_page: 10
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params
    if @course.save
      flash[:notice] = t "flash_course_created"
      redirect_to supervisor_course_path @course
    else
      render :new
    end
  end

  def show
    @activities = @course.load_activities
  end

  def edit
  end

  def update
    if course_params.has_key? :update_status
      @course.update_status!
      if @course.started?
        flash[:success] = t ".success", action: "Started"
      else
        flash[:success] = t ".success", action: "Finished"
      end
      redirect_to supervisor_course_path @course
    elsif @course.update_attributes course_params
      flash[:success] = t ".success", action: "Updated"
      redirect_to supervisor_course_path @course
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    flash[:success] = t ".course_delete"
    redirect_to supervisor_courses_path
  end

  private
  def load_course
    @course = Course.find params[:id]
  end

  def course_params
    params.require(:course).permit :name, :description, :start_date, :end_date,
      :update_status, subject_ids: []
  end  

  def check_course_before_update
    if @course.invalid_for_update? course_params.has_key?(:update_status)
      flash[:danger] = t ".danger"
      redirect_to supervisor_courses_path
    end
  end

  def check_course_before_destroy
    unless @course.finished?
      flash[:danger] = t ".danger"
      redirect_to supervisor_courses_path
    end
  end
end

app/controllers/supervisor/courses_subjects_controller.rb
class Supervisor::CoursesSubjectsController < ApplicationController
  before_action :load_courses_subject
  before_action :check_courses_subject, only: [:edit, :update]
  load_and_authorize_resource :course

  def show
    @course = @courses_subject.course
    @subject = @courses_subject.subject
    @tasks = @courses_subject.tasks
  end

  def edit
  end

  def update
    if courses_subject_params.has_key? :update_status
      update_status!
      redirect_to supervisor_course_courses_subject_path(
        id: @courses_subject.id, course_id: @courses_subject.course.id)
    else
      if @courses_subject.update_attributes courses_subject_params
        redirect_to supervisor_course_courses_subject_path(
          id: @courses_subject.id, course_id: @courses_subject.course.id)
      else
        render :edit
      end  
    end    
  end

  private
  def load_courses_subject
    @courses_subject = CoursesSubject.find params[:id]
  end

  def courses_subject_params
    params.require(:courses_subject).permit :update_status, task_ids: []
  end

  def update_status!
    if @courses_subject.new?
      @courses_subject.status = CoursesSubject::STATUS[:started]
      @courses_subject.users = @courses_subject.course.trainees
    elsif @courses_subject.started?
      @courses_subject.status = CoursesSubject::STATUS[:finished]
    end
    @courses_subject.save!
  end

  def check_courses_subject
    course = @courses_subject.course
    if course.finished? || ((course.started? || @courses_subject.started?) && 
      !courses_subject_params.has_key?(:update_status)) ||
      @courses_subject.finished?

      flash[:danger] = t ".danger"
      redirect_to supervisor_courses_path
    end
  end
end

app/controllers/supervisor/subjects_controller.rb
class Supervisor::SubjectsController < ApplicationController
  before_action :load_subject, only: [:edit, :update, :destroy]
  load_and_authorize_resource :course

  def index
    @search = Subject.search params[:q]
    @subjects = @search.result.paginate page: params[:page], per_page: 15
  end

  def show
    @subject = Subject.find params[:id]
    @tasks = @subject.tasks
    @subject_activities = PublicActivity::Activity.order("created_at desc").
      where trackable_type: "Subject", trackable_id: @subject.id
  end

  def new
    @subject = Subject.new
    @subject.tasks.build
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      redirect_to supervisor_subjects_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      redirect_to supervisor_subjects_path
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    redirect_to supervisor_subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit :id, :name, :description,
      tasks_attributes: [ :id, :name, :subject_id, :_destroy]
  end

  def load_subject
    @subject = Subject.find params[:id]
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < ApplicationController
  def index
    @users = User.all.paginate page: params[:page], per_page: 15
    if params[:supervisor] == User::TYPES[:supervisor]
      @search = User.supervisor.search params[:q]
      @users = @search.result.paginate page: params[:page], per_page: 15
    elsif params[:supervisor] == User::TYPES[:trainee]
      @search = User.trainee.search params[:q]
      @users = @search.result.paginate page: params[:page], per_page: 15
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = t ".delete_confirmation"
    redirect_to supervisor_users_path
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
  def link_to_add_fields(name, f, association, cssClass, title)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, child_index:
      "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to_function(name, "add_fields(this, \"#{ association }\",
      \"#{ escape_javascript(fields) }\")", class: cssClass, title: title,
      remote: true)
  end

  def link_to_remove_fields name, f
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_function name, function, html_options={}
    onclick = "#{"#{html_options[:onclick]}; " if
      html_options[:onclick]}#{function}; return false;"
    href = html_options[:href] || '#'
    content_tag :a, name, html_options.merge(href: href, onclick: onclick)
  end
end

app/views/supervisor/subjects/_subjects_activities.html.erb
<div class="panel panel-default">
  <div class="panel-body">
  <h2><%= t "title_activities" %></h2>
    <table class= "table table-striped">
      <% @subject_activities.each do |subject_activity| %>
        <tr>
          <td>
            <%= @subject.name.camelize %>
            <% key = subject_activity.key %>
            <%= key[8,key.length] << "d by" %>
            <% first_name = subject_activity.owner.first_name %>
            <% last_name = subject_activity.owner.last_name %>
            <%= link_to "#{first_name+" "+last_name}", current_user %>
            <%= time_ago_in_words(subject_activity.created_at) %>
            <%= t "activity_message_ago" %>
          </td>
        </tr>
      <% end %>
    </table>    
  </div>
</div>

app/views/supervisor/subjects/_task_fields.erb
<tr class="member">
  <td>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: t(".name_placeholder") %>
    </div>
  </td>
  <td>
    <div class="form-group">
      <%= link_to_remove_fields t(".remove_button"), f %>
    </div>
  </td>
</tr>

app/views/supervisor/subjects/edit.html.erb
<h1><%= t ".edit" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:supervisor, @subject] do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control"%>
      </div>
      <div class="field">
        <%= f.label :tasks %>
        <table>
          <tbody>
            <%= f.fields_for :tasks do |builder| %>
              <%= render "task_fields", f: builder %>
            <% end %>
          </tbody>
        </table>
        <div>
          <%= link_to_add_fields t(".add_more_button"), f, :tasks,
            "btn btn-primary", t(".add_more_button") %>
        </div>
      </div>
      <br><br>
      <center><%= f.submit class: "btn btn-primary" %></center>
    <% end %>
  </div>
</div>

app/views/supervisor/subjects/index.html.erb
<div class="row">
  <h1 class="text-capitalize"><%= t ".list" %></h1>
  <br>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t ".name" %></th>
        <th><%= t ".desc" %></th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <%= search_form_for [:supervisor, @search] do |f| %>
      <div class="form-group" >
        <%= f.label :name_cont %>
        <%= f.text_field :name_cont %>
        <%= f.submit t "search_button" %>
      </div>
    <% end %>
    <%= will_paginate renderer: BootstrapPagination::Rails %>
    <% @subjects.each do |subject| %>
      <tr>
        <td> <%= link_to "#{subject.name.camelize}", supervisor_subject_path(subject) %></td>
        <td><%= subject.description%></td>
        <td><%= link_to t(".edit_link"), edit_supervisor_subject_path(subject) %></td>
        <td><%= link_to t(".delete_link"), supervisor_subject_path(subject),
          method: :delete, data: {confirm: t(".delete_confirm")} %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= link_to t(".create"), new_supervisor_subject_path, class: "btn btn-primary" %>
</div>

app/views/supervisor/subjects/new.html.erb
<h1><%= t ".add" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:supervisor, @subject] do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :tasks %>
        <table>
          <tbody>
            <%= f.fields_for :tasks do |builder| %>
              <%= render "task_fields", f: builder %>
            <% end %>
          </tbody>
        </table>
        <div>
          <%= link_to_add_fields t(".add_more_in_add"), f, :tasks,
            "btn btn-primary", t(".add_more_in_add") %>
        </div>
      </div>
      <br><br>
      <center><%= f.submit class: "btn btn-primary" %></center>
    <% end %>
  </div>
</div>

app/views/supervisor/subjects/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      <%= @subject.name.camelize %>
    </h1>
  </div>
  <div class="panel-body">
    <%= @subject.description %>
  </div>
  <div class="panel-body">
    <% @tasks.each do |task| %>
      <div class="panel-footer">
        <%= task.name.camelize %>
      </div>
    <% end %>
  </div>
  <%= render "subjects_activities" %>
</div>